// import { Navbar } from "@/components";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>My-Shop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {/* <Navbar /> */}
        <div>
          Lorem ipsum, dolor sit amet consectetur adipisicing elit. Error harum voluptate, possimus
          dignissimos debitis, sequi pariatur nulla repellat nobis eligendi necessitatibus
          voluptates repudiandae impedit maiores nemo animi repellendus aperiam quas. Error harum,
          vero blanditiis sequi amet odio quidem architecto voluptate rerum tempora numquam dolorem
          excepturi eum magni eligendi nesciunt unde? Veniam sequi nostrum eveniet enim
          necessitatibus totam vel at velit! Incidunt voluptatibus dolore quis sequi rerum ipsam
          obcaecati, in laboriosam mollitia impedit aut ipsum totam aspernatur, enim inventore
          labore, modi nisi minima atque eligendi architecto perspiciatis qui? Deleniti, consequatur
          officia! Natus voluptatibus voluptates dolore consequuntur. Sequi necessitatibus vel
          itaque, officia iure, laboriosam architecto harum, ipsam omnis dolore excepturi veniam
          repudiandae voluptatum. Incidunt deleniti dolores neque nesciunt porro facilis dolore a?
          Inventore libero nulla maiores. Sit quae cumque velit, commodi saepe consectetur
          perferendis quo eligendi reiciendis sequi repudiandae tempore deleniti nobis. Blanditiis
          dignissimos numquam earum magni? Voluptate quod animi minus libero. Ipsam labore
          repellendus tempore ut, libero consectetur consequuntur iste unde molestiae dignissimos,
          maiores facilis vitae doloremque? Vitae dolorem accusantium ipsum cum ad consectetur
          veniam corporis, dolorum nesciunt nam velit harum. Quisquam ipsam ipsa est ducimus vero
          necessitatibus quos rem, at tempora sint, possimus porro aspernatur? Repellendus esse
          provident, voluptates, quibusdam debitis ullam, non voluptatem labore fugit quo dolore.
          Cum, voluptate! Repellat ratione placeat, iste assumenda quaerat commodi voluptatum esse
          totam fugiat fugit ex eveniet unde voluptatem ipsam eius omnis facilis vitae repellendus
          ipsa quisquam tempora accusantium consectetur! Ipsam, a quam! Laboriosam unde, alias
          doloremque veniam, culpa magni ut reprehenderit ipsam facilis, fuga corporis neque dicta
          quae obcaecati! Iure a quod adipisci aut reiciendis? Amet accusamus tempora fuga
          similique? Laboriosam, nihil? Aut ipsam dolorum quis neque ipsum repellat accusantium
          aperiam asperiores aliquid velit vitae reprehenderit et illo laudantium itaque enim quod,
          nobis fugiat voluptate rerum fugit tempora veritatis voluptatem animi. Minus! Enim rem
          aliquid tenetur distinctio quod obcaecati, odit id sequi, laboriosam officia, deleniti
          eligendi omnis ut soluta esse? Optio praesentium aliquam voluptas voluptatem nam deleniti
          nesciunt culpa pariatur iure vitae? Dolorum natus enim quo asperiores quisquam maxime
          fugiat, deleniti, dolores in porro consequatur iusto ipsa, nobis odio totam repudiandae
        </div>
      </main>
    </>
  );
}
